ministryofjustice/hmpps-architecture-as-code

- .github/workflows/pull_request.yml
- src/main/kotlin/prison/delius.kt
Adds a GitHub Action to validate PRs conform to the `.editorconfig` we've specified. This might also fix whitespace/tab/newlines... maybe.
To automatically format & lint our code, preventing divergence.
> Add EditorConfig GitHub Action

- src/main/kotlin/prison/nomis.kt
Tidy up of names for DPS components
Reflect where we are now.
> Tidy up of DPS services - remove custody api - remove nomis api - rename offender events to prisoner offender events

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/NationalPrisonRadio.kt
- src/main/kotlin/model/PrisonerContentHub.kt
This PR adds National Prison Radio and the nginx proxy to Prisoner Content Hub:
It also does a minor tweak for readability/maintainability to shift systems to alphabetically-sorted, one-per-line.
- Improves maintainability of workspace definition
- Adds National Prison Radio external system
> Add NPR to Prisoner Content Hub

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/CloudPlatform.kt
- src/main/kotlin/model/Heroku.kt
- src/main/kotlin/model/MoJSignOn.kt
- src/main/kotlin/model/PrisonVisitsBooking.kt
This change the first pass at adding the Prison Visits Booking (usually referred to as "PVB") to the model.
As its dependency "MoJ SignOn" is deployed in Heroku, I added it as a deployment node as well 🎉.
This pull request is phase one; I will extend these views with users once I can.
| System context diagram | Container diagram |
| --- | --- |
| ![structurizr-56937-prison-visits-booking-context](https://user-images.githubusercontent.com/1526295/89908472-d1ad2300-dbe5-11ea-83aa-778b023e6f65.png) | ![structurizr-56937-prison-visits-booking-container](https://user-images.githubusercontent.com/1526295/89926377-b4d01a00-dbfc-11ea-9a29-3ddad0124404.png) |
To document all systems in production.
> Add prison visits booking system (without users)

- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/PrepareCaseForCourt.kt
Factored out **Prepare a Case for Court** into dedicated `HMPPSSoftwareSystem`
To adopt new pattern and model the containers within the service
> Modelled Prepare a Case for Court

- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/IM.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/OASys.kt
This pull request normalises the relationships defined in the model to the pattern of
- "this system uses the other system for"
- "this person uses this system for"
Closes #51. On re-reading, I was confused by the "other system uses this system" pattern.
> Define system relationships in the source system

- src/main/kotlin/model/OASys.kt
Updates the Offender Assessment API details
Provide correct repo and swagger docs for the Offender Assessment API
> Update Offender Assessments API repo and swagger docs

- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/NOMIS.kt
Updates swagger URLs
To keep documentation current
> Update swagger URLs and add the probation search indexer

- decisions/interventions/0001-split-ui-and-service.md
- decisions/interventions/0002-decouple-with-events.md
Mark intervention ADRs as accepted
These decisions were in effect accepted during the pull request reviews, so formalising this
> Mark intervention ADRs as accepted

- decisions/interventions/0003-use-git-commits-to-explain-our-work.md
Adds an ADR for Interventions, where we decide that as a team we care about creating a good Git commit history. See commit message for more details.
To establish a way of working that will make the codebase more understandable to us and future developers on the project.
> Add an ADR for Interventions about Git commits

- decisions/interventions/0003-use-git-commits-to-explain-our-work.md
> Fix typo in ADR

- src/main/kotlin/annotations/Tags.kt
- src/main/kotlin/defineStyles.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/Interventions.kt
Add probation offender events app, API and SNS topic.
To make this app, API and topic more visible.
> Add probation offender events app and API

- src/main/kotlin/model/Interventions.kt
Update the Interventions system to the current state.
The in-progress interventions containers have GitHub repositories and no longer need the "planned" tag.
> Add in-progress interventions containers

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/AssessRisksAndNeeds.kt
- src/main/kotlin/model/OASys.kt
Adds details of the assess-risks-and-needs services. 
Expands out the OASys context a little.
> Access risks and needs

- src/main/kotlin/model/Interventions.kt
- src/main/kotlin/model/Reporting.kt
Refreshes the intervention model and diagrams to reflect the current state.
ℹ️ 👀 Please see commit messages in order for more details.
To keep the model up-to-date.
> Update interventions context and landscape

- src/main/kotlin/model/Interventions.kt
Updates the name of the interventions service to "Refer and monitor an intervention".
Reflects the latest decision by the stakeholders and service owner.
> Update the name of the interventions service

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/Delius.kt
- Adds the new Delius API application 
- Updates the Delius containers to reflect the move to CloudPlatform
- Creates a deployment view for nDelius
- Updating the Delius model to reflect the current state
> Update Delius containers and add Delius API

- src/main/kotlin/model/ManagePOMCases.kt
Update MPC Service
remove unnecessary API "container"
revise description for main application container
> Simplify Offender Management Allocation Manager model

- src/main/kotlin/defineDocumentation.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/PrisonerMoney.kt
* Adds Component and Context views for the Prisoner Money Services 
* To add the Prisoner Money Services to the hmpps-architecture-as-code documentation corpus
https://github.com/ministryofjustice/money-to-prisoners-transaction-uploader has its README in a reStructured Text format rather than markdown, causing an error in `src/main/kotlin/defineDocumentation.kt::readAPIDocsURLFromRepoReadmeBadge`. As this service (well, cron job to be precise) does not contain an API, and therefore no API documentation, we handle this case gracefully enough via an exception handler.
> Initial commit of Prisoner Money Context/Component

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/AssessRisksAndNeeds.kt
- src/main/kotlin/model/OASys.kt
Moves the ARN model into the same package as the rest of the elements
Consistency
> Move AssessRisksAndNeeds into the architecture package

- src/main/kotlin/model/AssessRisksAndNeeds.kt
- src/main/kotlin/model/OASys.kt
The read and write API layers around OASys are entirely separate. 
This PR adds the offender-updates to the OASys container diagram, and connects ARN up to it.
> ARN/OASys Offender Updates Service

- src/main/kotlin/model/AssessRisksAndNeeds.kt
Auto-correct linting problem with `ktlint -F "src/**/*.kt"`
Missed due to not rebasing the previous PR.
Make the build 🟢
> Auto-correct linting problem

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/HMPPSDomainEvents.kt
Create new HMPPS-Domain-Events system
> HMPPS_domain_events_initial_model

- src/main/kotlin/model/Interventions.kt
Use global domain events topic in interventions
It uses the one introduced now introduced to the model in 8ffb6b7f6a26add98ff03b94efe05561d788c597
To move towards the current state
> Use global domain events topic in interventions

- .github/workflows/build.yml
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
Upgrades kotlin, libraries and gradle to latest versions
Also switches the CI build to use Java 11
Keeping up-to-date
> Upgrade kotlin, libraries and gradle

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/ComplexityOfNeed.kt
Add reference to HMPPS-DOMAIN EVENTS topic
> Complexity_of_Need_Microservice

- .github/workflows/build.yml
- README.md
- script/generate_images.sh
Test image generation script as well -- the plantuml changes in the recent CLI mean that we can't have any description for our models any more, newlines are sensitive
To make sure all aspects of the app remain running
> Test image generation script as well

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/Curious.kt
Add new entry for Curious application
create a more complete model of HMPPS application landscape
> New entry for Curious Software System

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/ManageASupervision.kt
- src/main/kotlin/model/ManageSupervisions.kt
Adds the [Manage Supervisions](https://github.com/ministryofjustice/hmpps-manage-supervisions) service to the architecture diagrams. System Context, and Container diagrams are defined.
> Manage supervisions

- src/main/kotlin/model/ManageASupervision.kt
Adds a dynamic diagram (aka data flow, or sequence) for the Manage a Supervision service, showing how data flows between the various components
To add to our project documentation for security review, ITHC etc.
The image generator automatically generated both images above - personally I prefer the first one, the sequence diagram style, but I guess both will be created on structurizr.
> Dynamic diagram for Manage a Supervision

- src/main/kotlin/model/PrisonerContentHub.kt
Adds the Google Data Studio and Analytics workflows to the Prisoner Content Hub container and deployment diagrams
This updates the diagrams to reflect the current architecture for the Prisoner Content Hub.
> Introduces feedback uploaded job to prisoner content hub

- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/TierService.kt
Adds the Tier Service software system and containers into the model
To document the  Tier Service
> Document Tier Service

- src/main/kotlin/defineGlobalViews.kt
- src/main/kotlin/model/AssessRisksAndNeeds.kt
- src/main/kotlin/model/Azure.kt
- src/main/kotlin/model/BookVideoLink.kt
- src/main/kotlin/model/ComplexityOfNeed.kt
- src/main/kotlin/model/Curious.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/Interventions.kt
- src/main/kotlin/model/ManagePOMCases.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/PrisonerContentHub.kt
- Adds named Azure deployment environments
- Updates the deployment environment for the Curious software system to a named Azure environment
- Specifies the deployment environments for existing deployment diagram rather than relying on the default
- Ensure deployment views only include environments that are relevant
> Specify Deployment Environments

- src/main/kotlin/model/ManageRecalls.kt
Adding Auth service
To have a complete picture.
> Added Auth service relationships

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/AdjudicationsApi.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/DigitalPrisonServices.kt
Add Adjudications services 
Make sure the new services are documented
> NN-3819: Add Adjudications services

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/UseOfForce.kt
Adds models for use-of-force and required dependencies
To produce diagrams for documentation purposes
> Adding initial model for use-of-force

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineDocumentation.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/documentation/codeTracker.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/git.kt
Add a report that exposes how many unmerged branches exist (with commits that are not reachable from origin/{main,master}) and what is the oldest unmerged commit
Expose how long code that might be useful on production sits around
This is **not** meant to generate blame, more just visibility of work that has been started or done but not yet in production
> Report on stale branches

- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/Interventions.kt
- Updates to the latest terminologies (CRS vs Dynamic Framework, etc.)
- Separates NDMIS and Analytical Platform collectors
- Adds https://github.com/ministryofjustice/hmpps-delius-interventions-event-listener
| --- | --- |
| ![structurizr-56937-interventions-container](https://user-images.githubusercontent.com/1526295/147081355-c83ba881-3ec4-4c70-bb93-4636b694e4c8.png) | ![structurizr-56937-interventions-container](https://user-images.githubusercontent.com/1526295/147081452-cb784455-8e2b-4d7c-be56-d8345b3ba11f.png)  |
To be up-to-date with reality.
> Update interventions model

- exports/.gitignore
- script/generate_images.sh
Updates dependencies used by the image generator.
| --- | --- |
|  ![structurizr-56937-interventions-container](https://user-images.githubusercontent.com/1526295/147082863-80f0d91b-a4d2-43f2-973a-59c277a644e8.png) | ![structurizr-56937-interventions-container](https://user-images.githubusercontent.com/1526295/147082980-3a3cacf8-04bd-4201-b417-ae0c1b6168ef.png) |
To keep up-to-date and benefit from quality-of-life changes in those dependencies.
> Upgrade image generator dependencies

- script/generate_images.sh
- Upgrades the CLI version 
- Formats the image generation script using `shfmt`
General housekeeping
> Upgrade CLI version

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineStyles.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
Adds a colour scheme and some other small format changes. I'm not tied to the specific colours  
Visually differentiating components
> Add a colour scheme

- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/AssessRisksAndNeeds.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/Azure.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/OASys.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/views/HMPPSDataAPI.kt
> Update ARN deployments and data

- README.md
Add developer portal transition notice
To signpost other ways of compiling an org-wide view
> Add developer portal transition notice

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/StaffLookupApi.kt
Add Staff Lookup service
To social Staff Lookup service exists
> WFP-1553 added staff lookup

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/ProbationAllocationTool.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/ProbationPractitioners.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/WMT.kt
Adds and updates software artefacts owned by the Manage a Workforce team
Make it clearer to the rest of HMPPS where the software artefacts owned by the Manage a Workforce team sit
> WFP-1812: Add Manage a Workforce artefacts

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineDocumentation.kt
> Ab dmc test

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineDocumentation.kt
Reads the documentation file contents for display
Display the markdown documentation in the Structurizr UI
> Read documentation file contents

- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/AssessRisksAndNeeds.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/UnpaidWorkService.kt
Adds some additional containers to UPW
To complete the documentation of these services
> Adds containers to UPW, straightens names for ARN API

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/HMPPSAudit.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/MakeARecallDecision.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/UnpaidWorkService.kt
Adds a simple representation of the HMPPS Audit service and links MRD and UPW to it.
> Adds simple representation of HMPPS Audit service, links UPW and MRD

- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/Delius.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/MakeARecallDecision.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/UnpaidWorkService.kt
Adds MRD and UPW Integration services to Delius
To show how documents/data get from MRD and UPW services into Delius
> Adds MRD and UPW Integration Services to Delius

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineWorkspace.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/ConsiderARecall.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/CreateAndVaryALicence.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/Delius.kt
- Renames Make A Recall Decision to Consider A Recall
- Adds Redis to Consider A Recall
- Adds Create And Vary A Licence
- Adds Create And Vary A Licence to Consider A Recall
To align Consider A Recall documentation with the real world
> Consider a recall updates
