- src/main/kotlin/prison/model.kt
- src/main/kotlin/prison/pathfinder.kt
- src/main/kotlin/prison/views.kt
- src/main/kotlin/probation/delius.kt
- src/main/kotlin/probation/model.kt
- src/main/kotlin/probation/workspace.kt
We defined the "National Delius" software system in both packages and workspaces. This changeset moves DRYs that up by moving it to probation.
Slightly related change: `Community API` now has a space in its name, following the pattern of `Elite2 API`.
To reduce duplication in the model by reusing elements.
> Share Delius definition across HMPPS

- src/main/kotlin/prison/hmppsAuth.kt
- src/main/kotlin/prison/nomis.kt
- src/main/kotlin/prison/prisonerContentHub.kt
- src/main/kotlin/prison/views.kt
- src/main/kotlin/prison/workspace.kt
- Adds the Prisons enterprise
- Sets `Location.Internal`/`Location.External` on some systems in the prison space
- Adds a description for the Drupal DB container to remove a build warning
- Copies view layout options from probation to improve the layout of the prisoner content hub diagrams
The use of `Enterprise` and `Location` allows Structurizr to place an organisational boundary around the people and containers.
System Landscape diagram:
System Context diagram:
To demonstrate the use of Location to show organisational ownership, as an alternative to tags.
> Content hub improvements

- src/main/kotlin/prison/nomis.kt
- src/main/kotlin/prison/pathfinder.kt
- src/main/kotlin/prison/prisonerContentHub.kt
- src/main/kotlin/prison/views.kt
Renames Elite2 API to Prison API. The team renamed it on 3 July 2020.
To keep the information up-to-date.
> Rename Elite2 API to Prison API

- src/main/kotlin/shared/styles.kt
Change the text colour of people to match systems.
| --- | --- |
| <img width="300" src="https://user-images.githubusercontent.com/1526295/87686436-66a23500-c77c-11ea-92f6-8ef147f04ae4.png"/> | <img width="330" src="https://user-images.githubusercontent.com/1526295/88037751-391f0800-cb3d-11ea-8124-800e97591d18.png"/> |
To make the text on `Person` elements more legible.
> People should have the same text colour as systems

- README.md
Changes the Readme to link and show the `system-overview` diagram of the new merged workspace instead of prison and probation ones.
I forgot this change in #38  😅
> Change the Readme to link to the new merged workspace

- README.md
Adds example code on how to link to diagrams from GitHub repos.
[Container diagram source](https://github.com/ministryofjustice/hmpps-architecture-as-code/search?q=nomiscontainer)
To make it easier to link back to these diagrams from the code repositories.
> Add example code on how to link to diagrams from GitHub repos

- src/main/kotlin/defineModelWithDeprecatedSyntax.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/EPF.kt
- src/main/kotlin/model/IM.kt
- src/main/kotlin/model/InterventionTeams.kt
Groups teams working on intervention development, design, running into a single model object called `InterventionTeams`. As a result, the interactions by those teams are now in the relevant systems.
Make it easier to see which teams work on interventions.
> Group intervention teams together

- src/main/kotlin/defineModelWithDeprecatedSyntax.kt
- src/main/kotlin/defineWorkspace.kt
Automatically propagates C4 person-to-container relationships to C4 person-to-system relationships.
This propagation is useful to show who uses our systems to an audience outside the developer teams.
I noticed this was not happening when I was looking through the system context diagrams.
| --- | --- |
| ![structurizr-56937-prisonerContentHubSystemContext-before](https://user-images.githubusercontent.com/1526295/89526465-b73b0a00-d7df-11ea-9f47-276d47d9dcf5.png) | ![structurizr-56937-prisonerContentHubSystemContext-after](https://user-images.githubusercontent.com/1526295/89526456-b4d8b000-d7df-11ea-8ccf-9f7fee2c2493.png) |
For reference, the container diagram is:
Some of the person-to-container relationships that are defined in the `defineModelEntities` were not …
> Use implied relationships for all relationships

- src/main/kotlin/model/PrisonerContentHub.kt
Moves the Prisoner Content Hub NPR proxy to only proxy NPR requests, removing it from the "frontend"flow.
This proxy has been refactored to reduce the surprise factor of proxying certain paths off to different services. We now use domain separation to silo all our proxies, separating that from the rest of the frontend (i.e. media-proxy.content-hub.prisoner.service.justice.gov.uk/npr-stream,  rather than cookhamwood.content-hub.prisoner.service.justice.gov.uk/npr-stream).
To reflect changes to the system that have just been made.
> Prisoner Content Hub media proxy only proxies NPR

- src/main/kotlin/defineModelWithDeprecatedSyntax.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/IM.kt
- src/main/kotlin/model/InterventionTeams.kt
Clarifies the interactions between the teams using the Interventions Manager system, specifying that it's used for accredited programmes, not all interventions.
This pull request also defines the role of supporting teams who handle the accredited programme changes.
| --- | --- |
| ![structurizr-56937-interventions-manager-context](https://user-images.githubusercontent.com/1526295/89315671-0a437e80-d673-11ea-9e9e-753995cd4d00.png) | ![structurizr-56937-interventions-manager-context](https://user-images.githubusercontent.com/1526295/89905073-97418700-dbe1-11ea-90fc-316b726ce7ea.png) |
To be more specific on what is happening and getting closer to what _actually_ is happening. 😅
Source of change: process maps done by our business analysts and my notes from previous …
> Specify Intervention Manager interactions in more detail

- src/main/kotlin/defineModelWithDeprecatedSyntax.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/EPF.kt
- src/main/kotlin/model/InterventionTeams.kt
Consolidate other intervention-related roles to the `InterventionTeams` class.
One of the labels is slightly rephrased. No other changes in the model and diagrams.
Their roles are tied to delivering interventions, so they belong to that group.
> Move contract/programme managers to InterventionTeams

- src/main/kotlin/APIDocs.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/HMPPSAuth.kt
- src/main/kotlin/model/Licences.kt
- src/main/kotlin/model/ProbationTeamsService.kt
Adds the https://github.com/ministryofjustice/probation-teams API to the model.
This pull request introduces the `APIDocs` class, which sets the Structurizr property `api-docs-url`. Please refer to the full details in ba50bf5ce3c65f245ff73859e9e9f98347e8d615.
To make sure we can discover all APIs from this repository.
- licences app
- Please see ba50bf5ce3c65f245ff73859e9e9f98347e8d615
- I think the `APIDocs` object solves this -- anything with an API docs link is an API.
> Add probation teams API (and APIDocs)

- src/main/kotlin/model/OASys.kt
- src/main/kotlin/model/PrepareCaseForCourt.kt
Defines https://github.com/ministryofjustice/offender-assessments-api in the model.
It's a crucial API exposing assessment data from the OASys database. It's on the same level as `community-api` (Delius) and `prison-api` (NOMIS).
To make sure we have all widely used APIs documented.
> Define offender-assessments-api

- src/main/kotlin/defineViews.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/Pathfinder.kt
Adds GitHub and API docs URLs to the probation offender search service.
Please review commit-by-commit, the last commit changes the way of referencing C4 elements as the first commit renames an element:
- from `model.getSoftwareSystemByName("something")`
- to `ModelObject.something`
To have GitHub and API docs links available on as many items as possible.
> Add GitHub and API docs URLs to the probation offender search service

- exports/.gitignore
- src/main/kotlin/defineDocumentation.kt
- src/main/kotlin/defineWorkspace.kt
Generates and publishes a list of APIs that are tagged with `APIDocs` in the model to https://structurizr.com/share/56937/documentation (once this PR is merged).
This list is derived from annotating the architecture model, so it **won’t be** another list that has to be maintained in isolation.
To show something in the list, annotate the C4 container with the `APIDocs` class:
(once we settle on a convention in GitHub repos, we may pull this information directly **from the repos**)
https://github.com/ministryofjustice/hmpps-architecture-as-code/blob/2a0425bf778f59af00bb1788cbde0b7cddebb34d/src/main/kotlin/model/HMPPSAuth.kt#L19-L26
It looks like this in my test workspace:
Documentation is generated to `{repo_root}/exports/docs` during the `defineWorkspace` call:
```
$ cat …
```
> Publish API documentation to Structurizr

- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/NOMIS.kt
Adds API docs to Delius `community-api` (related to https://github.com/ministryofjustice/community-api/pull/242)
Adds API docs to NOMIS `prisoner-offender-search` and `prison-api`s.
To make sure we have as many APIs documented and published in #61 as possible.
> Add API docs to Delius and NOMIS containers

- README.md
Adds a "key outputs" section to the readme:
https://github.com/ministryofjustice/hmpps-architecture-as-code/blob/4d51ab7cf4f167ab9d630b11260122b2bf4cf0dc/README.md#key-outputs
I felt we were missing the articulation of what kinds of needs we were addressing with this repository.
This is a first attempt to define those.
> Define key outputs from this architecture model

- src/main/kotlin/defineWorkspace.kt
Adds the "Workload Management Tool" back to the model. It's defined in code, but not added to the "list of model items" in `defineWorkspace()`.
In the future, it would be great if all these model items could appear without manual maintenance, but no effort is made here to resolve that.
😱 I forgot to add it to the list earlier in 7d8346a23b44099e58d441756a02645bdcdc1e5f.
> Re-instate WMT in the list of systems

- src/main/kotlin/defineViews.kt
Removes authentication systems with many connections from the system overview; that diagram is mainly for showing how everything interactions and in that case, sign-on capabilities are not significant.
Following discussions in #65.
| --- | --- |
| ![system-overview-before](https://user-images.githubusercontent.com/1526295/91319701-94838c00-e7b4-11ea-9d3a-0d7d69252927.png) | ![system-overview-after](https://user-images.githubusercontent.com/1526295/91319704-951c2280-e7b4-11ea-9f9d-6def53392f36.png) |
These systems have _many_ connections, and they provide any significant detail in the overview diagram. If we remove them, it simplifies the view.
> Remove authentication systems from the overview diagram

- src/main/kotlin/OutsideHMPPS.kt
- src/main/kotlin/ProblemArea.kt
- src/main/kotlin/Tags.kt
- src/main/kotlin/addTo.kt
- src/main/kotlin/defineGlobalViews.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/HMPPSAuth.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/NationalPrisonRadio.kt
- src/main/kotlin/model/OffenderManagementInCustody.kt
- src/main/kotlin/model/PrepareCaseForCourt.kt
- src/main/kotlin/model/PrisonerContentHub.kt
Adds an abstraction called `OutsideHMPPS` which can be used to mark systems or people. This makes it easier to define what's included in HMPPS and what isn't.
This abstraction also automatically applies to `Tags.PROVIDER`, which reduces the burden of having to remember to also mark providers as external entities.
Anything that is defined in the model __but__ not marked as "outside" is automatically converted to "inside".
🙏 Please review commit-by-commit.
💠 The main benefit is the consistency of diagrams (assuming #67 will be merged).
| --- | --- |
| ![system-overview-before](https://user-images.githubusercontent.com/1526295/91323063-5c7e4800-e7b8-11ea-865f-4964cdcce21b.png) | ![system-overview-after](https://user-images.githubusercontent.com/1526295/91323066-5e480b80-e7b …
> Make HMPPS 'enterprise' boundary consistent

- README.md
Use publicly accessible API page link in the readme.
The `/workspace` variant is only available for Structrizr users with access. It's better to use a link everyone can see 😄
> Use publicly accessible API page link in the readme

- src/main/kotlin/model/PrepareCaseForCourt.kt
Changes _HMCTS Crime Portal_ to be categorised as a system outside HMPPS, but not as a system which is provided by 3rd parties. Now that #68 introduced `OutsideHMPPS`, we can now make this distinction.
I feel the nature of a government-provided service is better captured this way. For me green means "contracted private companies". What do you think, @markberridge?
On the rendered diagrams, this will make the system blueish rather than green.
| --- | --- |
| ![prepare-case-context-old](https://user-images.githubusercontent.com/1526295/91439341-b2102e80-e864-11ea-98e7-debbd8851c10.png) | ![structurizr-55488-prepare-case-context-new](https://user-images.githubusercontent.com/1526295/91439346-b3d9f200-e864-11ea-906d-8678ce84e2f5.png) |
The HM Courts and Tribunals is a …
> Mark HMCTS system as "outside" instead of "provider"

- src/main/kotlin/annotations/APIDocs.kt
- src/main/kotlin/annotations/OutsideHMPPS.kt
- src/main/kotlin/annotations/ProblemArea.kt
- src/main/kotlin/annotations/Tags.kt
- src/main/kotlin/annotations/addTo.kt
- src/main/kotlin/defineGlobalViews.kt
- src/main/kotlin/defineStyles.kt
- src/main/kotlin/model/CRCSystem.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/EPF.kt
- src/main/kotlin/model/EQuiP.kt
- src/main/kotlin/model/HMPPSAuth.kt
- src/main/kotlin/model/IM.kt
- src/main/kotlin/model/InterventionTeams.kt
- src/main/kotlin/model/MoJSignOn.kt
- src/main/kotlin/model/NID.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/NationalPrisonRadio.kt
- src/main/kotlin/model/OASys.kt
- src/main/kotlin/model/Pathfinder.kt
- src/main/kotlin/model/PrepareCaseForCourt.kt
- src/main/kotlin/model/PrisonVisitsBooking.kt
- src/main/kotlin/model/PrisonerContentHub.kt
- src/main/kotlin/model/ProbationPractitioners.kt
- src/main/kotlin/model/ProbationTeamsService.kt
- src/main/kotlin/model/Reporting.kt
Moves all constructs responsible for "annotating" a model object to a separate package so they can be viewed in a single place as a "library".
I was wondering (in the context of https://github.com/ministryofjustice/laa-architecture-as-code) if I were new to the repository, would I know what "annotations" were available to use with the model? Are they discoverable?
These questions led to moving these to a single package; the next step would be documentation about their expected effects.
> Move "annotations" to their own package

- src/main/kotlin/model/OASys.kt
Makes "OASys" more visible on diagrams by using its abbreviation instead of its full name.
On diagrams, I was automatically looking for "OASys" -- the term is embedded into our vocabulary now, so (I feel) it's better to see it on the title right away.
> Swap OASys name and expanded acronym

- src/main/kotlin/defineGlobalViews.kt
- src/main/kotlin/model/CaseNotesToProbation.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/NDH.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/OASys.kt
I stumbled across the [NDH Replacement][page] wiki page and it describes NDH in detail.
This change reflects the content on the wiki.
fe71e72339d449733acf2315bbab2c8265d9f85c explicitly declares the relationships between software systems that are _enabled_ by NDH:
> NDH has the characteristics of a 'hub'-like system. It either pulls from or pushes to OASys, nDelius and NOMIS.
>
> These relationships make sense, however, if we want to have high-level view, this communication pattern creates noise.
>
> If we assume NDH to be a "protocol" instead of "system" for the purposes of high-level views, we can map out the relationships enabled by the system (`defineImpliedRelationships()`).
>
> For more detailed views, we can keep the implementation details.
It sounded sensible to call it out …
> Update NDH relationships

- src/main/kotlin/model/NDH.kt
Corrects the use of custody-api in the context of the existing NDH.
The existing NDH implementation uses "XTAG queues", the replacement was planning to use custody-api.
> Replace custody-api with XTAG queues in context of NDH

- src/main/kotlin/model/WMT.kt
Corrects the name behind the `WMT` acronym.
I recently saw a screenshot of the tool and it was using "Workload Measurement Tool", so it must be the correct one.
> Use the correct name behind WMT acronym

- src/main/kotlin/defineModelWithDeprecatedSyntax.kt
- src/main/kotlin/model/OffenderManagementInCustody.kt
Adds a new container view, focussed on offender management in custody. The model was already there but I didn't export a view.
Naming and placement of elements in the model were also corrected.
**Result**
To be able to present an up-to-date OMiC container context directly via image links.
> Add "offender management in custody" container view

- src/main/kotlin/model/Delius.kt
Updates the community-api API docs, based on changes in https://github.com/ministryofjustice/community-api/pull/274#pullrequestreview-503701850.
Using non-VPN links makes life better for everyone 🎉 
We could now _parse_ the link from the repository directly...
> Update to a non-VPN community-api API docs link

- src/main/kotlin/defineGlobalViews.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/Azure.kt
- src/main/kotlin/model/AzureADTenantJusticeUK.kt
- src/main/kotlin/model/HMPPSAuth.kt
* Adds a system context diagram for HMPPS-Auth
* Adds the Azure deployment environment
* Adds the AzureAD Justice UK tenant which contains DOM1 identities 
Visualising the authentication environment and adding a new identity provider system
> Add Azure deployment environment and AzureAD Justice tenant

- src/main/kotlin/defineModelWithDeprecatedSyntax.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/EPF.kt
- src/main/kotlin/model/EQuiP.kt
- src/main/kotlin/model/PolicyTeams.kt
Captures how policy is updated in EQuiP and adds a new system context diagram.
To make sure we can see how government policy is updated. As EQuiP is also the source of the process maps, it's an interesting hub of business change.
> Capture that policy changes are recorded in EQuiP

- src/main/kotlin/annotations/Tags.kt
- src/main/kotlin/defineStyles.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/AnalyticalPlatform.kt
- src/main/kotlin/model/HMPPSAuth.kt
- src/main/kotlin/model/InterventionTeams.kt
- src/main/kotlin/model/Interventions.kt
Defines the target architecture for the new dynamic framework digital service.
ℹ️ Everything faded out is `planned` and does not exist yet -- up for debate and review.
⚠️ I arranged this diagram manually. The generated layout has the same nodes but quite a useless layout 😢 I'm working on that on a separate branch.
- `community-api` will have to change
- `intervention-probation-translator` may be done within `community-api` itself; it depends whether we can work together, or need to do push to other services ourselves
To be able to share the existing thinking around what's required for integration and what the first pass will be for the beta phase.
> Adds first pass of planned intervention architecture (it will evolve)

- build.gradle.kts
- decisions/interventions/0001-split-ui-and-service.md
- decisions/interventions/0002-decouple-with-events.md
- src/main/kotlin/DefinesDecisions.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/main.kt
- src/main/kotlin/model/DigitalPrisonsNetwork.kt
- src/main/kotlin/model/Interventions.kt
- src/main/kotlin/model/Pathfinder.kt
- src/main/kotlin/model/PrisonerContentHub.kt
- src/main/kotlin/model/ProbationTeamsService.kt
Defines the initial proposed ADRs for interventions, which extend the initial architecture in #83.
I am using the [structurizr-adr-tools][adr-tools] library to parse all ADRs in the `decisions/interventions` folder.
A new `DefinesDecisions` interface is an optional extension to `HMPPSSoftwareSystem`; both can be used on anything defined in `MODEL_ITEMS`.
The decisions will be published in Structurizr under its [decision log][log] page: https://structurizr.com/share/56937/decisions (which is currently empty until this is merged). It will look something like this:
The ADR contents are
- [decisions/interventions/0001-split-ui-and-service.md](https://github.com/ministryofjustice/hmpps-architecture-as-code/blob/interventions-decisions/decisions/interventions/0001-split-ui-and-service.md)
- …
> Add interventions architecture decision records

- decisions/interventions/0003-use-git-commits-to-explain-our-work.md
Extend the git ADR in interventions with a decision around not using merge commits in PR branches.
This reflects a conversation we had as a team.
> Decide not to use merge commits in Interventions

- .github/CODEOWNERS
Change ownership of `decisions/interventions/` contents to the interventions team.
Having ADRs specific to a software system shared here has its benefits. One of the drawbacks is notifying _all_ reviewers when they change.
That model may work if we have processes around reviewing decisions at this level, but for now, it's noise for the rest of the owners.
For now, only notify/require reviews on system-specific decisions from the system owner team.
> Transfer ownership of decisions to the owner team

- src/main/kotlin/annotations/APIDocs.kt
- src/main/kotlin/defineDocumentation.kt
- src/main/kotlin/git.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/HMPPSAuth.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/ProbationTeamsService.kt
- src/main/kotlin/pullADRs.kt
During the build, the app now fetches API documentation URLs from application readmes.
✨ New steps:
1. Clones the application repositories referenced in the model.
2. Greps the `README.md` file for an "API docs" badge.
3. If it exists, extracts the API docs URL.
Existing steps:
4. Creates an `exports/docs/apidocs.md` file with all the apps.
5. Publishes the result to [Structurizr](https://structurizr.com/share/56937/documentation#%2F:Published%20APIs) after merges.
**Requirements**
- Only works with publicly cloneable repos
- Picks up [![API docs](https://img.shields.io/badge/API_docs_-view-85EA2D.svg?logo=swagger)](https://example.org) badges:
```
[![API docs](https://img.shields.io/badge/API_docs-view-85EA2D.svg?logo=swagger)](https://link.to/swagger)
```
- More specifically, has to …
> Fetch API documentation URLs from application readmes

- src/main/kotlin/model/PrisonerContentHub.kt
This updates the architecture diagram to show the ICEcast relay we now have running for prison radio in-cell.
> Update prison radio proxy tech to match reality

- src/main/kotlin/model/PrisonerContentHub.kt
This PR:
1. Merges the youth and adult person, because their roles are the same for the prisoner content hub. At the moment there's no difference to how we serve the two groups, so it doesn't feel worth having the extra complexity in our diagrams
2. Shows prisoner devices connect directly to S3. We applied this a while back but I didn't update it here 🤦. This change reduced load on the Drupal pods 🥳 .
> Prisoner content hub s3 prisoner access

- src/main/kotlin/model/Delius.kt
Document how the probation search indexer receives updates to the offender records.
Taken from its [readme](https://github.com/ministryofjustice/probation-offender-search-indexer).
To be up-to-date.
> Add how the probation search indexer receives data

- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/Interventions.kt
- src/main/kotlin/model/Reporting.kt
Reflect plans around interventions &rarr; reporting pipeline.
1. The ownership of the "transfer area" will sit with interventions. (Removes the landing bucket from `Reporting`)
2. A new SAP BODS component will scoop the data up. (Creates a new ETL container in `Reporting`)
Note: there is a potential that interventions can use the Analytical Platform landing bucket for this purpose. We still need to confirm that the proposed usage of the Analytical Platform is in line with the owners.
Additionally, clarified how NDMIS acquires data from nDelius.
To reflect the current state.
> Reflect plans around interventions->reporting pipe

- src/main/kotlin/model/NOMIS.kt
Remove hardcoded API docs URL
The build said
```
[git] Processing https://github.com/ministryofjustice/prisoner-offender-search
[defineDocumentation] overriding API docs URL
- from https://prisoner-offender-search.prison.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
- to   https://prisoner-offender-search-dev.prison.service.justice.gov.uk/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
```
which means it's defined in its README, so we no longer need to define it in the model 🎉 
Remove hardcoding in favour of teams self-defining all their stuff.
> Remove hardcoded API docs URL

- script/generate_images.sh
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/model/EPF.kt
- src/main/kotlin/model/NID.kt
- src/main/kotlin/model/NOMIS.kt
- src/main/kotlin/model/Pathfinder.kt
- src/main/kotlin/model/ProbationCaseSampler.kt
- src/main/kotlin/model/Reporting.kt
Update CLI to latest version for better generated PlantUML diagrams
The new version however does not support new lines in descriptions, please see b3aa202 for details
For better diagrams:
| --- | --- |
| ![structurizr-56937-interventions-container](https://user-images.githubusercontent.com/1526295/118319105-39382c00-b4f2-11eb-9232-a91b1a6414e5.png) | ![structurizr-56937-interventions-container](https://user-images.githubusercontent.com/1526295/118318853-dc3c7600-b4f1-11eb-9cab-2041e4b5273f.png)
|![structurizr-56937-interventions-deployment](https://user-images.githubusercontent.com/1526295/118319100-36d5d200-b4f2-11eb-9913-5b8694daf6f6.png) | ![structurizr-56937-interventions-deployment](https://user-images.githubusercontent.com/1526295/118318863-de9ed000-b4f1-11eb-957b- …
> Update CLI to latest version for better generated PlantUML diagrams

- src/main/kotlin/defineDocumentation.kt
- src/main/kotlin/git.kt
- src/main/kotlin/model/Delius.kt
- src/main/kotlin/pullADRs.kt
1. Finds all containers with github/ministryofjustice `url`s
2. Clones them
3. Reads the circleci orb version from `.circleci/config.yml`
4. Reads the gradle-sprint-boot version from `build.gradle.kts`
5. Generates `exports/docs/dependencies.md`
6. Will publish it to https://structurizr.com/share/56937/documentation
I removed the `git pull` functionality as it was terribly slow. CI will pull fresh anyway
Generated file: https://gist.github.com/sldblog/bb171733565523e0469c62dca3772ddb:
Make collecting and updating shared library data easier than spreadsheets :)
> Dependency report

- src/main/kotlin/annotations/Tags.kt
- src/main/kotlin/defineStyles.kt
- src/main/kotlin/defineWorkspace.kt
- src/main/kotlin/model/AssessRisksAndNeeds.kt
- src/main/kotlin/model/PrepareCaseForSentence.kt
- src/main/kotlin/model/UserPreferenceApi.kt
Models updates which have been made to the Prepare a Case for Sentence service
- Rename the service from **Prepare a Case for Court** to **Prepare a Case for Sentence**
- Prepare a Case for Sentence now uses **User Preferences** service
- The **Crime Portal Mirror Gateway** JBoss has been replaced by a Kotlin + Spring **Crime Portal Gateway**
- **Crime Portal Gateway** has supporting AWS S3 and SQS
- Update the model
> Updates to Prepare a Case for Sentence

- .github/dependabot.yml
Add dependabot for dependency version tracking
Get notified and update out of date dependencies, once a week
> Add dependabot for dependency version tracking

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineDocumentation.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/documentation/versionTracker.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/git.kt
Add helm chart dependency tracking to https://structurizr.com/share/56937/documentation/*#2
The main changes are in 2de6aa01cad5b69cd33d2e0918919d7c5368eee2
To expose how up to date services are with the shared libraries/charts we provide
> Add helm chart dependency tracking

- .github/workflows/publish.yml
🐛 Use the same Java version in publish as in CI to fix the publishing failure:
This was missed in 95cd49ec3a5daaf955d8ab2c6e1ad78b5f73a734
Currently causing problems after #158:
`Error: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jgit/api/errors/GitAPIException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`
> 🐛 Use the same Java version in publish as in CI

- src/main/kotlin/uk/gov/justice/hmpps/architecture/defineDocumentation.kt
- src/main/kotlin/uk/gov/justice/hmpps/architecture/documentation/versionTracker.kt
Render multiple items in dependencies with commas
And also don't do that during data gathering but only rendering
To fix the rendering of multiple dependencies: the "newline" was stripped, so the current version is garbled together. This version separates the entries with `, `.
| --- | --- |
|  <img width="605" alt="image" src="https://user-images.githubusercontent.com/1526295/144270533-4b9c48c6-1840-43dc-882d-702f33962ee5.png"> | <img width="563" alt="image" src="https://user-images.githubusercontent.com/1526295/144270810-140a8ebe-dc38-4ce9-a43a-3bfa3b7f363b.png"> |
> Render multiple items in dependencies with commas

- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/UseOfForce.kt
Edits user relationships for coordinator and reviewer in the model for use-of-force
Stating the intent of these users for posterity as suggested in the following recent PR: https://github.com/ministryofjustice/hmpps-architecture-as-code/pull/160
> Edited description of user relationships in Use of Force model

- src/main/kotlin/uk/gov/justice/hmpps/architecture/model/AssessRisksAndNeeds.kt
Adds API and area tags 
Include the risks and needs service in the API views
> Add API tags to risks and needs service

- .github/dependabot.yml
- renovate.json5
Switch to Renovate, so updates are grouped in one PR
Reduce maintenance PR volume.
> Switch to Renovate so updates are grouped in one PR
